# Generated by Django 4.1.2 on 2023-04-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dartsplayer',
            old_name='user_id',
            new_name='id',
        ),
    ]
