# Generated by Django 4.1.2 on 2023-04-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0002_rename_user_id_dartsplayer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dartsplayer',
            name='T20_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dartsplayer',
            name='darts_thrown',
            field=models.IntegerField(default=0),
        ),
    ]
