# Generated by Django 4.1.2 on 2023-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0003_dartsplayer_t20_count_dartsplayer_darts_thrown'),
    ]

    operations = [
        migrations.AddField(
            model_name='dartsplayer',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
