# Generated by Django 4.1.2 on 2023-04-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0004_dartsplayer_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='dartsplayer',
            name='darts_won',
            field=models.IntegerField(default=0),
        ),
    ]
