# Generated by Django 4.1.2 on 2023-04-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0005_dartsplayer_darts_won'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dartsplayer',
            old_name='darts_won',
            new_name='games_won',
        ),
    ]
